In [1]:
import pandas as pd
df = pd.read_csv("./data/raw/Base.csv")

In [2]:
# Dropping anonymized columns
columns_to_drop = ['payment_type', 'employment_status', 'housing_status']
df = df.drop(columns=columns_to_drop)

In [3]:
df.describe()

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,zip_count_4w,velocity_6h,...,phone_mobile_valid,bank_months_count,has_other_cards,proposed_credit_limit,foreign_request,session_length_in_minutes,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.0,1000000.000000
mean,0.011029,0.562696,0.493694,16.718568,86.587867,33.689080,1.025705e+00,8.661499,1572.692049,5665.296605,...,0.889676,10.839303,0.222988,515.851010,0.025242,7.544940,0.576947,1.018312,0.0,3.288674
std,0.104438,0.290343,0.289125,44.046230,88.406599,12.025799,5.381835e+00,20.236155,1005.374565,3009.380665,...,0.313293,12.116875,0.416251,487.559902,0.156859,8.033106,0.494044,0.180761,0.0,2.209994
min,0.000000,0.100000,0.000001,-1.000000,-1.000000,10.000000,4.036860e-09,-15.530555,1.000000,-170.603072,...,0.000000,-1.000000,0.000000,190.000000,0.000000,-1.000000,0.000000,-1.000000,0.0,0.000000
25%,0.000000,0.300000,0.225216,-1.000000,19.000000,20.000000,7.193246e-03,-1.181488,894.000000,3436.365848,...,1.000000,-1.000000,0.000000,200.000000,0.000000,3.103053,0.000000,1.000000,0.0,1.000000
50%,0.000000,0.600000,0.492153,-1.000000,52.000000,30.000000,1.517574e-02,-0.830507,1263.000000,5319.769349,...,1.000000,5.000000,0.000000,200.000000,0.000000,5.114321,1.000000,1.000000,0.0,3.000000
75%,0.000000,0.800000,0.755567,12.000000,130.000000,40.000000,2.633069e-02,4.984176,1944.000000,7680.717827,...,1.000000,25.000000,0.000000,500.000000,0.000000,8.866131,1.000000,1.000000,0.0,5.000000
max,1.000000,0.900000,0.999999,383.000000,428.000000,90.000000,7.845690e+01,112.956928,6700.000000,16715.565404,...,1.000000,32.000000,1.000000,2100.000000,1.000000,85.899143,1.000000,2.000000,0.0,7.000000

In [4]:
# The column 'device_fraud_count' contains only the value 0 for all cases (constant)
df = df.drop(columns='device_fraud_count')

In [5]:
df['is_internet'] = df['source'] == 'INTERNET'
df = df.drop(columns = 'source')

In [6]:
df['is_windows_or_mac'] = df['device_os'].isin(['windows', 'macintosh'])
df = df.drop(columns = 'device_os')

In [7]:
df.dtypes

fraud_bool                            int64
income                              float64
name_email_similarity               float64
prev_address_months_count             int64
current_address_months_count          int64
customer_age                          int64
days_since_request                  float64
intended_balcon_amount              float64
zip_count_4w                          int64
velocity_6h                         float64
velocity_24h                        float64
velocity_4w                         float64
bank_branch_count_8w                  int64
date_of_birth_distinct_emails_4w      int64
credit_risk_score                     int64
email_is_free                         int64
phone_home_valid                      int64
phone_mobile_valid                    int64
bank_months_count                     int64
has_other_cards                       int64
proposed_credit_limit               float64
foreign_request                       int64
session_length_in_minutes           float64
keep_alive_session                    int64
device_distinct_emails_8w             int64
month                                 int64
is_internet                            bool
is_windows_or_mac                      bool
dtype: object

In [8]:
df.to_csv('./data/raw/Base_cleaned.csv', index=False)

In [9]:
df

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,zip_count_4w,velocity_6h,...,bank_months_count,has_other_cards,proposed_credit_limit,foreign_request,session_length_in_minutes,keep_alive_session,device_distinct_emails_8w,month,is_internet,is_windows_or_mac
0,0,0.3,0.986506,-1,25,40,0.006735,102.453711,1059,13096.035018,...,9,0,1500.0,0,16.224843,1,1,0,True,False
1,0,0.8,0.617426,-1,89,20,0.010095,-0.849551,1658,9223.283431,...,2,0,1500.0,0,3.363854,1,1,0,True,False
2,0,0.8,0.996707,9,14,40,0.012316,-1.490386,1095,4471.472149,...,30,0,200.0,0,22.730559,0,1,0,True,True
3,0,0.6,0.475100,11,14,30,0.006991,-1.863101,3483,14431.993621,...,1,0,200.0,0,15.215816,1,1,0,True,False
4,0,0.9,0.842307,-1,29,40,5.742626,47.152498,2339,7601.511579,...,26,0,200.0,0,3.743048,0,1,0,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0,0.8,0.124690,-1,143,30,0.051348,-0.826239,530,6732.602414,...,31,0,1500.0,0,16.967770,0,1,7,True,False
999996,0,0.9,0.824544,-1,193,30,0.009591,0.008307,408,1574.293294,...,-1,1,1000.0,0,1.504109,0,1,7,True,True
999997,0,0.8,0.140891,-1,202,10,0.059287,50.609995,749,1258.864938,...,31,0,200.0,0,16.068595,0,1,7,True,False
999998,0,0.9,0.002480,52,3,30,0.023357,-1.313387,707,7048.137128,...,1,0,200.0,0,1.378683,1,1,7,True,False
999999,0,0.6,0.993391,-1,174,30,0.020422,14.942456,655,3737.076479,...,15,1,200.0,0,1.947926,1,1,7,True,False